name: First CI
on: 
push:
jobs:
  test:
  run-on: ubuntu-latest
  steps:
  - name: Get code
  uses: actions/checkout@v4
  - name: Install python
  uses: action/setup-python@v5
  with:
  python-version: "3.12"
  - name: Install pytest
  run: pip install pytest
- name: run tests
run: pytest
